# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('x_coord', models.DecimalField(decimal_places=3, max_digits=5)),
                ('y_coord', models.DecimalField(decimal_places=3, max_digits=5)),
                ('img_name', models.CharField(max_length=100)),
                ('light_data', models.IntegerField()),
                ('battery_level', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
