# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.5 on 2017-10-13 00:14
from __future__ import unicode_literals

from django.db import migrations, models
=======
# Generated by Django 1.11.5 on 2017-10-15 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> bdf99018b15b95790b8821b7d8a2bf40f52f6374


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> bdf99018b15b95790b8821b7d8a2bf40f52f6374
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('x_coord', models.DecimalField(decimal_places=3, max_digits=5)),
                ('y_coord', models.DecimalField(decimal_places=3, max_digits=5)),
                ('img_name', models.CharField(max_length=100)),
                ('light_data', models.IntegerField()),
                ('battery_level', models.DecimalField(decimal_places=2, max_digits=5)),
=======
            name='TOTPDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('step', models.PositiveSmallIntegerField(default=30)),
                ('t0', models.BigIntegerField(default=0)),
                ('last_t', models.BigIntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> bdf99018b15b95790b8821b7d8a2bf40f52f6374
            ],
        ),
    ]
