# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosky', '0002_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
