# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosky', '0003_userprofile_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('img_name', models.CharField(max_length=100)),
                ('light_data', models.IntegerField()),
                ('battery_level', models.FloatField()),
            ],
        ),
    ]
